//! Deterministic generator for the checked-in built-in program reference.

use std::collections::{BTreeMap, BTreeSet};
use std::ffi::OsString;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use clipasm::reference::{
    self, BodyInitialValueRole, BodyOutputs, BuiltinCategory, BuiltinProgram, Cardinality,
    DiagnosticCategory, DiagnosticReference, RelatedReference, TimelineBehavior,
};

const GENERATED_MARKER: &str =
    "<!-- Generated by clipasm-reference-docs. Do not edit directly. -->";
const PROGRAM_SUMMARY_START: &str = "<!-- BEGIN GENERATED PROGRAM REFERENCE NAVIGATION -->";
const PROGRAM_SUMMARY_END: &str = "<!-- END GENERATED PROGRAM REFERENCE NAVIGATION -->";
const DIAGNOSTIC_SUMMARY_START: &str = "<!-- BEGIN GENERATED DIAGNOSTIC REFERENCE NAVIGATION -->";
const DIAGNOSTIC_SUMMARY_END: &str = "<!-- END GENERATED DIAGNOSTIC REFERENCE NAVIGATION -->";

type Result<T> = std::result::Result<T, String>;

/// Execute the generator's `write` or `check` mode.
///
/// # Errors
///
/// Returns a human-readable error for invalid arguments, catalog drift,
/// stale generated files, or filesystem failures.
pub fn run(arguments: impl IntoIterator<Item = OsString>) -> Result<()> {
    let arguments = arguments.into_iter().collect::<Vec<_>>();
    let [mode] = arguments.as_slice() else {
        return Err("usage: clipasm-reference-docs <write|check>".to_owned());
    };
    let mode = mode
        .to_str()
        .ok_or_else(|| "generator mode must be valid UTF-8".to_owned())?;
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .ok_or_else(|| "could not locate the ClipAsm repository root".to_owned())?;
    let generated = generate(root)?;
    match mode {
        "write" => {
            write_generated(root, &generated)?;
            println!(
                "updated {} built-in program and {} diagnostic reference pages",
                generated.program_pages.len(),
                generated.diagnostic_pages.len()
            );
            Ok(())
        }
        "check" => {
            check_generated(root, &generated)?;
            println!(
                "{} built-in program and {} diagnostic reference pages are current",
                generated.program_pages.len(),
                generated.diagnostic_pages.len()
            );
            Ok(())
        }
        _ => Err(format!(
            "unknown generator mode `{mode}`; expected `write` or `check`"
        )),
    }
}

#[derive(Debug)]
struct GeneratedReference {
    program_pages: BTreeMap<String, String>,
    diagnostic_pages: BTreeMap<String, String>,
    program_summary_block: String,
    diagnostic_summary_block: String,
}

fn generate(root: &Path) -> Result<GeneratedReference> {
    let programs = reference::builtin_programs();
    let diagnostics = reference::diagnostics();
    validate_program_catalog(root, &programs, diagnostics)?;
    validate_diagnostic_catalog(root, diagnostics)?;

    let mut program_pages = BTreeMap::new();
    program_pages.insert("index.md".to_owned(), render_index(&programs));
    for program in &programs {
        let file_name = format!("{}.md", program.name());
        if program_pages
            .insert(file_name.clone(), render_program(program))
            .is_some()
        {
            return Err(format!(
                "two built-in programs map to generated page `{file_name}`"
            ));
        }
    }

    let diagnostic_pages =
        BTreeMap::from([("index.md".to_owned(), render_diagnostic_index(diagnostics))]);

    validate_generated_links(root, &program_pages, &diagnostic_pages)?;
    validate_documented_codes(root, diagnostics)?;

    Ok(GeneratedReference {
        program_pages,
        diagnostic_pages,
        program_summary_block: render_program_summary_block(&programs),
        diagnostic_summary_block: render_diagnostic_summary_block(),
    })
}

fn validate_program_catalog(
    root: &Path,
    programs: &[BuiltinProgram],
    diagnostics: &[DiagnosticReference],
) -> Result<()> {
    if programs.is_empty() {
        return Err("built-in catalog is empty".to_owned());
    }

    let mut names = BTreeSet::new();
    let mut routes = BTreeSet::new();
    let mut categories = BTreeSet::new();
    for program in programs {
        if !names.insert(program.name()) {
            return Err(format!("duplicate built-in program `{}`", program.name()));
        }
        if !program
            .name()
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'_')
        {
            return Err(format!(
                "built-in program `{}` does not map to a safe stable route",
                program.name()
            ));
        }
        let route = program.documentation_route();
        if !routes.insert(route.clone()) {
            return Err(format!("duplicate built-in documentation route `{route}`"));
        }
        if route != format!("reference/programs/{}.html", program.name()) {
            return Err(format!(
                "built-in program `{}` has unexpected route `{route}`",
                program.name()
            ));
        }
        if program.summary().trim().is_empty() || program.summary().chars().any(char::is_control) {
            return Err(format!(
                "built-in program `{}` has an invalid summary",
                program.name()
            ));
        }
        categories.insert(program.category());
        validate_example(program)?;
        for related in program.related_programs() {
            if !names.contains(related.as_str())
                && !programs.iter().any(|candidate| candidate.name() == related)
            {
                return Err(format!(
                    "built-in program `{}` links to unknown related program `{related}`",
                    program.name()
                ));
            }
        }
        for diagnostic in program.diagnostics() {
            if reference::diagnostic(diagnostic).is_none() {
                return Err(format!(
                    "built-in program `{}` links to unregistered diagnostic code `{diagnostic}`",
                    program.name()
                ));
            }
        }
        for parameter in program.parameters() {
            if !parameter.is_required()
                && parameter.default().is_none()
                && parameter.omission_behavior().is_none()
            {
                return Err(format!(
                    "optional parameter `{}.{}` has neither a catalog default nor documented contextual behavior",
                    program.name(),
                    parameter.name()
                ));
            }
        }
    }

    let expected_categories = BuiltinCategory::ALL.into_iter().collect::<BTreeSet<_>>();
    if categories != expected_categories {
        return Err("one or more built-in program categories are empty".to_owned());
    }
    let registered_codes = diagnostics
        .iter()
        .map(|diagnostic| diagnostic.code())
        .collect::<BTreeSet<_>>();
    for program in programs {
        for code in program.diagnostics() {
            if !registered_codes.contains(code.as_str()) {
                return Err(format!(
                    "built-in program `{}` links to unregistered diagnostic code `{code}`",
                    program.name()
                ));
            }
        }
    }

    for path in [
        "docs/reference/language/stack-binding.md",
        "docs/reference/language/statements-and-calls.md",
        "docs/reference/cli.md",
    ] {
        if !root.join(path).is_file() {
            return Err(format!(
                "generated reference link target is missing: {path}"
            ));
        }
    }
    Ok(())
}

fn validate_diagnostic_catalog(root: &Path, diagnostics: &[DiagnosticReference]) -> Result<()> {
    if diagnostics.is_empty() {
        return Err("diagnostic catalog is empty".to_owned());
    }

    let mut codes = BTreeSet::new();
    let mut anchors = BTreeSet::new();
    let mut categories = BTreeSet::new();
    let mut previous_code = None;
    for diagnostic in diagnostics {
        let code = diagnostic.code();
        if previous_code.is_some_and(|previous| previous >= code) {
            return Err(format!(
                "diagnostic catalog is not ordered by code near `{code}`"
            ));
        }
        previous_code = Some(code);
        if !codes.insert(code) {
            return Err(format!("duplicate diagnostic code `{code}`"));
        }
        if !valid_diagnostic_code(code) {
            return Err(format!("diagnostic code `{code}` has an invalid format"));
        }
        categories.insert(diagnostic.category());
        for (field, value) in [
            ("title", diagnostic.title()),
            ("summary", diagnostic.summary()),
        ] {
            if value.trim().is_empty() || value.chars().any(char::is_control) {
                return Err(format!("diagnostic `{code}` has an invalid {field}"));
            }
        }
        for (field, values) in [
            ("common cause", diagnostic.common_causes()),
            ("recommended action", diagnostic.recommended_actions()),
        ] {
            if values
                .iter()
                .any(|value| value.trim().is_empty() || value.chars().any(char::is_control))
            {
                return Err(format!("diagnostic `{code}` has an invalid {field}"));
            }
        }

        let anchor = diagnostic.documentation_anchor();
        if anchor != diagnostic_anchor(code) {
            return Err(format!(
                "diagnostic `{code}` has unexpected documentation anchor `{anchor}`"
            ));
        }
        let route = diagnostic.documentation_route();
        let expected_route = format!("reference/diagnostics/index.html#{anchor}");
        if route != expected_route {
            return Err(format!(
                "diagnostic `{code}` has unexpected documentation route `{route}`"
            ));
        }
        if !anchors.insert((diagnostic.category(), anchor.clone())) {
            return Err(format!(
                "duplicate diagnostic anchor `{anchor}` in category `{}`",
                diagnostic.category().label()
            ));
        }
        for related in diagnostic.related_links() {
            validate_related_link(root, code, *related)?;
        }
    }

    let expected_categories = DiagnosticCategory::ALL.into_iter().collect::<BTreeSet<_>>();
    if categories != expected_categories {
        return Err("one or more diagnostic categories are empty".to_owned());
    }
    Ok(())
}

fn valid_diagnostic_code(code: &str) -> bool {
    code.len() > 2
        && code.starts_with("E_")
        && code
            .bytes()
            .all(|byte| byte.is_ascii_uppercase() || byte.is_ascii_digit() || byte == b'_')
}

fn diagnostic_anchor(code: &str) -> String {
    code.to_ascii_lowercase()
}

fn validate_related_link(root: &Path, code: &str, related: RelatedReference) -> Result<()> {
    let route = related.documentation_route();
    let source_route = route
        .split_once('#')
        .map_or(route, |(route, _)| route)
        .strip_suffix(".html")
        .map_or_else(|| route.to_owned(), |route| format!("{route}.md"));
    let source = root.join("docs").join(source_route);
    if related.label().trim().is_empty() || !source.is_file() {
        return Err(format!(
            "diagnostic `{code}` has invalid related reference `{}` -> `{route}`",
            related.label()
        ));
    }
    Ok(())
}

fn validate_example(program: &BuiltinProgram) -> Result<()> {
    let source = example_source(program);
    let path = PathBuf::from(format!("{}-reference.clipasm", program.name()));
    let package = clipasm::language::parse_str(&path, &source).map_err(|error| {
        format!(
            "built-in program `{}` example does not parse:\n{error}",
            program.name()
        )
    })?;
    let compiled = clipasm::compiler::compile(&package).map_err(|error| {
        format!(
            "built-in program `{}` example does not compile:\n{error}",
            program.name()
        )
    })?;
    if !compiled
        .explain()
        .iter()
        .any(|entry| entry.construct() == program.name())
    {
        return Err(format!(
            "built-in program `{}` example does not invoke that program",
            program.name()
        ));
    }
    let expectation = program.example_expectation();
    let actual_outputs = compiled
        .outputs()
        .iter()
        .map(|output| output.value_type())
        .collect::<Vec<_>>();
    if actual_outputs != expectation.outputs() {
        return Err(format!(
            "built-in program `{}` example produced {:?}, expected {:?}",
            program.name(),
            actual_outputs,
            expectation.outputs()
        ));
    }
    if let Some(expected_frames) = expectation.expected_frames() {
        let actual_frames = compiled
            .result_domain()
            .ok_or_else(|| {
                format!(
                    "built-in program `{}` example has no deterministic Video domain",
                    program.name()
                )
            })?
            .frames()
            .0;
        if actual_frames != expected_frames {
            return Err(format!(
                "built-in program `{}` example produced {actual_frames} frames, expected {expected_frames}",
                program.name()
            ));
        }
    }
    Ok(())
}

fn example_source(program: &BuiltinProgram) -> String {
    let project = if program.example_expectation().expected_frames().is_some() {
        "config {\n    video {\n        fps = 30\n    }\n}\n\n"
    } else {
        ""
    };
    format!("clipasm 1\n\n{project}{}\n", program.example().trim())
}

fn render_index(programs: &[BuiltinProgram]) -> String {
    let mut output = generated_header(
        "Programs and composition",
        "Use language composition forms to group work, and callable programs to create or transform Video and Audio values.",
    );
    output.push_str(
        "ClipAsm has three user-facing kinds of program-like building block:\n\n\
         - [`clip { ... }`](../language/composition-forms.md#clip) builds one reusable Video or Audio value and removes its temporary stack occurrence.\n\
         - [Stack blocks](../language/composition-forms.md#stack-blocks) group statements and may return one or several values.\n\
         - Callable programs use normal call syntax. Built-ins are listed below; imported source programs use the same call model.\n\n\
         `clip` and stack blocks are language forms, not registered callable programs, so `clipasm programs` lists only the built-ins below.\n\n\
         The type shapes below are lookup notation, not ClipAsm declaration syntax. See [statements and calls](../language/statements-and-calls.md) for authored syntax.\n\n\
         ## Callable built-ins\n\n",
    );
    for (index, category) in BuiltinCategory::ALL.into_iter().enumerate() {
        if index > 0 {
            output.push('\n');
        }
        writeln!(output, "### {}\n", category.label()).expect("write String");
        output.push_str("| Program | Summary | Type shape | Properties |\n");
        output.push_str("| --- | --- | --- | --- |\n");
        for program in programs
            .iter()
            .filter(|program| program.category() == category)
        {
            let properties = match (program.is_generic(), program.body().is_some()) {
                (true, true) => "generic; accepts a body",
                (true, false) => "generic",
                (false, true) => "accepts a body",
                (false, false) => "—",
            };
            writeln!(
                output,
                "| [`{0}`]({0}.md) | {1} | `{2}` | {3} |",
                program.name(),
                markdown_cell(program.summary()),
                markdown_cell(&type_shape(program)),
                properties,
            )
            .expect("write String");
        }
    }
    output
}

#[expect(
    clippy::too_many_lines,
    reason = "the linear renderer keeps one generated page's section order visible in one place"
)]
fn render_program(program: &BuiltinProgram) -> String {
    let mut output = generated_header(program.name(), program.summary());

    output.push_str("## Call shape\n\n");
    writeln!(output, "```text\n{}\n```\n", program.call_shape()).expect("write String");
    output.push_str("This is call-shape notation for lookup, not ClipAsm declaration syntax.\n\n");

    output.push_str("## Inputs\n\n");
    if program.inputs().is_empty() {
        output.push_str("This program has no graph-valued inputs.\n\n");
    } else {
        output.push_str("| Name | Type | Cardinality |\n| --- | --- | --- |\n");
        for input in program.inputs() {
            let cardinality = match input.cardinality() {
                Cardinality::One => "exactly one".to_owned(),
                Cardinality::Variadic { minimum } => format!("one or more (minimum {minimum})"),
                _ => "catalog-defined".to_owned(),
            };
            writeln!(
                output,
                "| `{}` | `{}` | {} |",
                input.name(),
                input.value_type(),
                cardinality
            )
            .expect("write String");
        }
        output.push('\n');
    }

    output.push_str("## Parameters\n\n");
    if program.parameters().is_empty() {
        output.push_str("This program has no scalar parameters.\n\n");
    } else {
        output.push_str("| Name | Type | Requirement | Default or omission behavior |\n");
        output.push_str("| --- | --- | --- | --- |\n");
        for parameter in program.parameters() {
            let requirement = if parameter.is_required() {
                "required"
            } else {
                "optional"
            };
            let default = if parameter.is_required() {
                "—".to_owned()
            } else {
                parameter.default().map_or_else(
                    || {
                        parameter
                            .omission_behavior()
                            .unwrap_or("No fixed default.")
                            .to_owned()
                    },
                    ToString::to_string,
                )
            };
            writeln!(
                output,
                "| `{}` | `{}` | {} | {} |",
                parameter.name(),
                markdown_cell(&parameter.parameter_type().to_string()),
                requirement,
                markdown_cell(&default)
            )
            .expect("write String");
        }
        output.push('\n');
    }

    output.push_str("## Outputs and binding\n\n");
    if program.outputs().is_empty() {
        output.push_str("This program produces no values.\n\n");
    } else {
        let outputs = program
            .outputs()
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(output, "Outputs: `{outputs}`.\n").expect("write String");
    }
    if program.is_generic() {
        output.push_str(
            "All `T` inputs and outputs use one homogeneous type: Video or Audio. \
             Use an explicit `<Video>` or `<Audio>` argument when the accessible \
             stack makes inference ambiguous.\n\n",
        );
    }
    writeln!(
        output,
        "Default stack access is **{}**. See [stack binding](../language/stack-binding.md) \
         for ownership and visibility rules.\n",
        program.stack_access()
    )
    .expect("write String");

    if let Some(body) = program.body() {
        output.push_str("## Body contract\n\n");
        output.push_str("The body begins with:\n\n");
        for initial in body.initial_values() {
            let role = match initial.role() {
                BodyInitialValueRole::Input { input } => {
                    format!("the complete `{input}` input")
                }
                BodyInitialValueRole::SelectedRange { input, parameter } => {
                    format!("the range selected from `{input}` by `{parameter}`")
                }
                _ => "a catalog-defined initial value".to_owned(),
            };
            writeln!(output, "- `{}` from {role}", initial.value_type()).expect("write String");
        }
        output.push_str("\nThe body must leave ");
        match body.outputs() {
            BodyOutputs::Exactly(outputs) => {
                let output_types = outputs
                    .iter()
                    .map(ToString::to_string)
                    .collect::<Vec<_>>()
                    .join(", ");
                write!(output, "exactly `{output_types}`").expect("write String");
            }
            BodyOutputs::Variadic {
                value_type,
                minimum,
            } => {
                write!(
                    output,
                    "at least {minimum} homogeneous `{value_type}` value(s)"
                )
                .expect("write String");
            }
            _ => output.push_str("the catalog-defined output sequence"),
        }
        output.push_str(".\n\n");
    }

    output.push_str("## Timeline behavior\n\n");
    writeln!(
        output,
        "{}\n",
        timeline_description(program.timeline_behavior())
    )
    .expect("write String");

    output.push_str("## Example\n\n");
    writeln!(output, "```clipasm\n{}```\n", example_source(program)).expect("write String");
    output.push_str("Expected validation result: ");
    let expectation = program.example_expectation();
    if expectation.outputs().is_empty() {
        output.push_str("no output values");
    } else {
        let outputs = expectation
            .outputs()
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(", ");
        write!(output, "`{outputs}`").expect("write String");
        if let Some(frames) = expectation.expected_frames() {
            write!(
                output,
                " with exactly {frames} project frames at the example's explicit `fps = 30`"
            )
            .expect("write String");
        } else if expectation.outputs() == [clipasm::model::ValueType::Video] {
            output.push_str(" with a source-dependent frame domain resolved during preflight");
        }
    }
    output.push_str(".\n\n");
    output.push_str(
        "This exact example is parsed and compiled by the reference checks; compilation \
         does not inspect the named media files.\n\n",
    );

    output.push_str("## Important behavior\n\n");
    for paragraph in program.behavior_notes() {
        writeln!(output, "- {paragraph}").expect("write String");
    }
    if program.behavior_notes().is_empty() {
        output.push_str("- The call follows the generated contract above.\n");
    }
    output.push('\n');

    if !program.constraints().is_empty() {
        output.push_str("## Constraints\n\n");
        for constraint in program.constraints() {
            writeln!(output, "- {constraint}").expect("write String");
        }
        output.push('\n');
    }

    if !program.diagnostics().is_empty() {
        output.push_str("## Selected diagnostics\n\n");
        output.push_str(
            "These are selected actionable diagnostics, not every error a call can produce.\n\n",
        );
        for code in program.diagnostics() {
            let diagnostic =
                reference::diagnostic(code).expect("validated built-in diagnostic reference");
            writeln!(
                output,
                "- [`{code}`](../diagnostics/index.md#{}) — {}",
                diagnostic.documentation_anchor(),
                diagnostic.title()
            )
            .expect("write String");
        }
        output.push('\n');
    }

    output.push_str("## Related reference\n\n");
    for related in program.related_programs() {
        writeln!(output, "- [`{related}`]({related}.md)").expect("write String");
    }
    output.push_str(
        "- [Statements and calls](../language/statements-and-calls.md)\n\
         - [Stack binding](../language/stack-binding.md)\n",
    );
    output
}

fn render_diagnostic_index(diagnostics: &[DiagnosticReference]) -> String {
    let mut output = generated_header(
        "Diagnostics",
        "Find the meaning of an error code and the next action to take.",
    );
    output.push_str(
        "The fastest lookup is the installed CLI:\n\n\
         ```console,ignore\n\
         clipasm explain E_UNKNOWN_PROGRAM\n\
         ```\n\n\
         The command works without opening a project or inspecting media. Use the sections below when browsing the book.\n\n",
    );
    output.push_str("## Areas\n\n| Area | Codes | Use this section for |\n");
    output.push_str("| --- | ---: | --- |\n");
    for category in DiagnosticCategory::ALL {
        let count = diagnostics
            .iter()
            .filter(|diagnostic| diagnostic.category() == category)
            .count();
        writeln!(
            output,
            "| [{}](#{}) | {} | {} |",
            category.label(),
            category.route(),
            count,
            diagnostic_category_summary(category),
        )
        .expect("write String");
    }
    output.push_str(
        "\nUse the exact code from the error. Wording and source notes may differ by ClipAsm version.\n\n",
    );

    for category in DiagnosticCategory::ALL {
        writeln!(
            output,
            "<a id=\"{}\"></a>\n\n## {}\n",
            category.route(),
            category.label()
        )
        .expect("write String");
        for diagnostic in diagnostics
            .iter()
            .filter(|diagnostic| diagnostic.category() == category)
        {
            render_diagnostic(&mut output, diagnostic);
        }
    }
    let content_end = output.trim_end().len();
    output.truncate(content_end);
    output.push('\n');
    output
}

fn render_diagnostic(output: &mut String, diagnostic: &DiagnosticReference) {
    writeln!(
        output,
        "<a id=\"{}\"></a>\n\n### `{}` — {}\n",
        diagnostic.documentation_anchor(),
        diagnostic.code(),
        diagnostic.title()
    )
    .expect("write String");
    writeln!(output, "{}\n", diagnostic.summary()).expect("write String");

    output.push_str("#### Common causes\n\n");
    for cause in diagnostic.common_causes() {
        writeln!(output, "- {cause}").expect("write String");
    }
    output.push_str("\n#### Try\n\n");
    for action in diagnostic.recommended_actions() {
        writeln!(output, "- {action}").expect("write String");
    }
    output.push_str("\n#### Retry\n\n");
    writeln!(output, "{}\n", diagnostic.retry_guidance().explanation()).expect("write String");

    if !diagnostic.related_links().is_empty() {
        output.push_str("#### Related reference\n\n");
        for related in diagnostic.related_links() {
            writeln!(
                output,
                "- [{}]({})",
                related.label(),
                related_markdown_route(related.documentation_route())
            )
            .expect("write String");
        }
        output.push('\n');
    }
}

fn diagnostic_category_summary(category: DiagnosticCategory) -> &'static str {
    match category {
        DiagnosticCategory::CommandLineAndProjects => {
            "CLI arguments, initialization, and inspection output"
        }
        DiagnosticCategory::ParsingAndSource => {
            "syntax, source layout, literals, and project configuration"
        }
        DiagnosticCategory::ImportsAndDeclarations => {
            "imports, declarations, names, and external definitions"
        }
        DiagnosticCategory::TypesAndStack => "arguments, types, output bindings, and stack inputs",
        DiagnosticCategory::CompilationAndTimelines => {
            "timeline ranges, placement names, and compile-time evaluation"
        }
        DiagnosticCategory::PreflightAndMedia => {
            "missing media, probing, decoding, and tool capabilities"
        }
        DiagnosticCategory::ExternalPrograms => {
            "external executable discovery, protocol, and execution"
        }
        DiagnosticCategory::RenderingAndPublication => {
            "rendering, outputs, manifests, and publication"
        }
        DiagnosticCategory::CacheAndFilesystem => {
            "paths, hashing, cache state, and filesystem access"
        }
        DiagnosticCategory::BrowserRuntime => "browser assets, limits, and browser render plans",
        DiagnosticCategory::InternalContractFailures => {
            "likely ClipAsm defects that should be reported"
        }
        _ => "diagnostics in this area",
    }
}

fn related_markdown_route(route: &str) -> String {
    let (path, fragment) = route
        .split_once('#')
        .map_or((route, None), |(path, fragment)| (path, Some(fragment)));
    let path = path
        .strip_suffix(".html")
        .map_or_else(|| path.to_owned(), |path| format!("{path}.md"));
    let mut relative = path
        .strip_prefix("reference/")
        .map_or_else(|| format!("../../{path}"), |path| format!("../{path}"));
    if let Some(fragment) = fragment {
        write!(relative, "#{fragment}").expect("write String");
    }
    relative
}

fn generated_header(title: &str, summary: &str) -> String {
    format!("{GENERATED_MARKER}\n\n# {title}\n\n{summary}\n\n")
}

fn type_shape(program: &BuiltinProgram) -> String {
    let inputs = program
        .inputs()
        .iter()
        .map(|input| match input.cardinality() {
            Cardinality::Variadic { .. } => format!("{}...", input.value_type()),
            _ => input.value_type().to_string(),
        })
        .collect::<Vec<_>>()
        .join(", ");
    let outputs = if program.outputs().is_empty() {
        "none".to_owned()
    } else {
        program
            .outputs()
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(", ")
    };
    format!("({inputs}) -> {outputs}")
}

fn timeline_description(behavior: &TimelineBehavior) -> String {
    match behavior {
        TimelineBehavior::Fresh => {
            "Creates a fresh timeline layout, or no layout when the program has no output."
                .to_owned()
        }
        TimelineBehavior::Identity { input } => {
            format!("Preserves the timeline layout of `{input}`.")
        }
        TimelineBehavior::Repeat { input } => format!(
            "`repeat(1)` preserves `{input}` as an identity. Larger counts create a fresh, \
             unindexed repeated timeline."
        ),
        TimelineBehavior::Concat { input } => {
            format!("Concatenates the ordered timeline layouts bound to `{input}`.")
        }
        TimelineBehavior::BodyConcat { inputs } => format!(
            "Initializes the body from {} and concatenates the homogeneous values it leaves.",
            inputs
                .iter()
                .map(|input| format!("`{input}`"))
                .collect::<Vec<_>>()
                .join(" and ")
        ),
        TimelineBehavior::Crop { input } => format!(
            "Crops `{input}` to the selected range and retains only placements proven to lie \
             completely inside it."
        ),
        TimelineBehavior::Replace { base } => format!(
            "Replaces the selected range in `{base}`, shifts later placements, and exposes the \
             inserted layout as `replacement`."
        ),
        TimelineBehavior::FlashCut { before, after } => format!(
            "Places `{before}` and `{after}` sequentially and exposes corresponding transition \
             regions."
        ),
        TimelineBehavior::Crossfade { before, after } => format!(
            "Overlaps the end of `{before}` with the start of `{after}` and exposes `before`, \
             `overlap`, and `after` regions."
        ),
        _ => "Uses the catalog-defined timeline behavior.".to_owned(),
    }
}

fn markdown_cell(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}

fn render_program_summary_block(programs: &[BuiltinProgram]) -> String {
    let mut output = format!("{PROGRAM_SUMMARY_START}\n");
    output.push_str("- [Programs and composition](reference/programs/index.md)\n");
    output.push_str("  - [`clip` and stack blocks](reference/language/composition-forms.md)\n");
    for program in programs {
        writeln!(
            output,
            "  - [`{0}`](reference/programs/{0}.md)",
            program.name()
        )
        .expect("write String");
    }
    output.push_str(PROGRAM_SUMMARY_END);
    output
}

fn render_diagnostic_summary_block() -> String {
    format!(
        "{DIAGNOSTIC_SUMMARY_START}\n- [Diagnostics](reference/diagnostics/index.md)\n{DIAGNOSTIC_SUMMARY_END}"
    )
}

fn validate_generated_links(
    root: &Path,
    program_pages: &BTreeMap<String, String>,
    diagnostic_pages: &BTreeMap<String, String>,
) -> Result<()> {
    for (file_name, page) in program_pages {
        for (target, anchor) in markdown_targets(page) {
            if let Some(target) = target.strip_prefix("../diagnostics/") {
                let target_name = target.to_owned();
                let target_page = diagnostic_pages.get(&target_name).ok_or_else(|| {
                    format!(
                        "generated program page `{file_name}` links to missing diagnostic page `{target_name}`"
                    )
                })?;
                if let Some(anchor) = anchor
                    && !target_page.contains(&format!("id=\"{anchor}\""))
                {
                    return Err(format!(
                        "generated program page `{file_name}` links to missing diagnostic anchor `#{anchor}`"
                    ));
                }
            }
        }
    }
    for (file_name, page) in diagnostic_pages {
        for (target, anchor) in markdown_targets(page) {
            if target.is_empty() {
                if let Some(anchor) = anchor
                    && !page.contains(&format!("id=\"{anchor}\""))
                {
                    return Err(format!(
                        "generated diagnostic page `{file_name}` links to missing local anchor `#{anchor}`"
                    ));
                }
                continue;
            }
            if target.starts_with("https://") {
                continue;
            }
            if let Some(target_page) = diagnostic_pages.get(target) {
                if let Some(anchor) = anchor
                    && !target_page.contains(&format!("id=\"{anchor}\""))
                {
                    return Err(format!(
                        "generated diagnostic page `{file_name}` links to missing anchor `#{anchor}` in `{target}`"
                    ));
                }
                continue;
            }
            let source_target = if let Some(target) = target.strip_prefix("../../") {
                root.join("docs").join(target)
            } else if let Some(target) = target.strip_prefix("../") {
                root.join("docs/reference").join(target)
            } else {
                root.join("docs/reference/diagnostics").join(target)
            };
            if !source_target.is_file() {
                return Err(format!(
                    "generated diagnostic page `{file_name}` links to missing target `{target}`"
                ));
            }
        }
    }
    Ok(())
}

fn markdown_targets(markdown: &str) -> Vec<(&str, Option<&str>)> {
    let mut targets = Vec::new();
    let mut remaining = markdown;
    while let Some(open) = remaining.find("](") {
        let after_open = &remaining[open + 2..];
        let Some(close) = after_open.find(')') else {
            break;
        };
        let raw = &after_open[..close];
        let (target, anchor) = raw
            .split_once('#')
            .map_or((raw, None), |(target, anchor)| (target, Some(anchor)));
        targets.push((target, anchor));
        remaining = &after_open[close + 1..];
    }
    targets
}

fn validate_documented_codes(root: &Path, diagnostics: &[DiagnosticReference]) -> Result<()> {
    let registered = diagnostics
        .iter()
        .map(|diagnostic| diagnostic.code())
        .collect::<BTreeSet<_>>();
    for source in markdown_files(root)? {
        let text = fs::read_to_string(&source)
            .map_err(|error| format!("could not read `{}`: {error}", source.display()))?;
        for code in diagnostic_codes_in(&text) {
            if !registered.contains(code.as_str()) {
                return Err(format!(
                    "{} mentions unregistered diagnostic code `{code}`",
                    source
                        .strip_prefix(root)
                        .unwrap_or(source.as_path())
                        .display()
                ));
            }
        }
    }
    Ok(())
}

fn markdown_files(root: &Path) -> Result<Vec<PathBuf>> {
    let mut files = Vec::new();
    for entry in fs::read_dir(root)
        .map_err(|error| format!("could not read `{}`: {error}", root.display()))?
    {
        let path = entry
            .map_err(|error| format!("could not inspect `{}`: {error}", root.display()))?
            .path();
        if path.is_file() && path.extension().is_some_and(|extension| extension == "md") {
            files.push(path);
        }
    }
    collect_markdown_files(&root.join("docs"), &mut files)?;
    files.sort();
    files.dedup();
    Ok(files)
}

fn collect_markdown_files(directory: &Path, files: &mut Vec<PathBuf>) -> Result<()> {
    for entry in fs::read_dir(directory)
        .map_err(|error| format!("could not read `{}`: {error}", directory.display()))?
    {
        let entry = entry.map_err(|error| {
            format!(
                "could not inspect Markdown files in `{}`: {error}",
                directory.display()
            )
        })?;
        let path = entry.path();
        if path.is_dir() {
            collect_markdown_files(&path, files)?;
        } else if path.extension().is_some_and(|extension| extension == "md") {
            files.push(path);
        }
    }
    Ok(())
}

fn diagnostic_codes_in(text: &str) -> BTreeSet<String> {
    let bytes = text.as_bytes();
    let mut codes = BTreeSet::new();
    let mut index = 0;
    while index + 2 < bytes.len() {
        if bytes[index] == b'E' && bytes[index + 1] == b'_' {
            let start = index;
            index += 2;
            while index < bytes.len()
                && (bytes[index].is_ascii_uppercase()
                    || bytes[index].is_ascii_digit()
                    || bytes[index] == b'_')
            {
                index += 1;
            }
            if index > start + 2 {
                codes.insert(text[start..index].to_owned());
            }
        } else {
            index += 1;
        }
    }
    codes
}

fn check_generated(root: &Path, generated: &GeneratedReference) -> Result<()> {
    reject_incomplete_transactions(root)?;
    let mut problems = Vec::new();
    check_generated_tree(
        root,
        "program",
        "docs/reference/programs",
        &generated.program_pages,
        &mut problems,
    )?;
    check_generated_tree(
        root,
        "diagnostic",
        "docs/reference/diagnostics",
        &generated.diagnostic_pages,
        &mut problems,
    )?;

    let summary_path = root.join("docs/SUMMARY.md");
    match fs::read_to_string(&summary_path) {
        Ok(summary) => {
            let expected = replace_summary_block(
                &summary,
                PROGRAM_SUMMARY_START,
                PROGRAM_SUMMARY_END,
                &generated.program_summary_block,
            )
            .and_then(|summary| {
                replace_summary_block(
                    &summary,
                    DIAGNOSTIC_SUMMARY_START,
                    DIAGNOSTIC_SUMMARY_END,
                    &generated.diagnostic_summary_block,
                )
            });
            match expected {
                Ok(expected) if expected == summary => {}
                Ok(_) => {
                    problems
                        .push("generated reference navigation in docs/SUMMARY.md differs".into());
                }
                Err(error) => problems.push(error),
            }
        }
        Err(error) => problems.push(format!("could not read docs/SUMMARY.md: {error}")),
    }

    if problems.is_empty() {
        Ok(())
    } else {
        Err(format!(
            "generated reference is stale:\n- {}",
            problems.join("\n- ")
        ))
    }
}

fn check_generated_tree(
    root: &Path,
    kind: &str,
    relative_directory: &str,
    expected_pages: &BTreeMap<String, String>,
    problems: &mut Vec<String>,
) -> Result<()> {
    let directory = root.join(relative_directory);
    if directory.is_dir() {
        let actual = fs::read_dir(&directory)
            .map_err(|error| format!("could not read `{}`: {error}", directory.display()))?
            .map(|entry| {
                entry.map_err(|error| format!("could not read generated directory entry: {error}"))
            })
            .collect::<Result<Vec<_>>>()?;
        let expected_names = expected_pages.keys().cloned().collect::<BTreeSet<_>>();
        for entry in actual {
            let file_name = entry.file_name().to_string_lossy().into_owned();
            if !expected_names.contains(&file_name) {
                problems.push(format!(
                    "obsolete or unowned generated path remains: {relative_directory}/{file_name}"
                ));
            }
        }
        for (file_name, expected) in expected_pages {
            let path = directory.join(file_name);
            match fs::read_to_string(&path) {
                Ok(actual) if actual == *expected => {}
                Ok(_) => problems.push(format!(
                    "generated bytes differ: {relative_directory}/{file_name}"
                )),
                Err(error) => problems.push(format!(
                    "could not read generated page `{relative_directory}/{file_name}`: {error}"
                )),
            }
        }
    } else {
        problems.push(format!("generated {kind} reference directory is missing"));
    }
    Ok(())
}
#[expect(
    clippy::too_many_lines,
    reason = "the transaction keeps staging, installation, and rollback for both generated trees visible together"
)]
fn write_generated(root: &Path, generated: &GeneratedReference) -> Result<()> {
    reject_incomplete_transactions(root)?;
    let reference_directory = root.join("docs/reference");
    let programs = reference_directory.join("programs");
    let diagnostics = reference_directory.join("diagnostics");
    let summary = root.join("docs/SUMMARY.md");
    let process = std::process::id();
    let staged_programs = reference_directory.join(format!(".programs-stage-{process}"));
    let backup_programs = reference_directory.join(format!(".programs-backup-{process}"));
    let staged_diagnostics = reference_directory.join(format!(".diagnostics-stage-{process}"));
    let backup_diagnostics = reference_directory.join(format!(".diagnostics-backup-{process}"));
    let staged_summary = root.join(format!("docs/.SUMMARY-stage-{process}"));
    let backup_summary = root.join(format!("docs/.SUMMARY-backup-{process}"));

    fs::create_dir(&staged_programs).map_err(|error| {
        format!(
            "could not create staging directory `{}`: {error}",
            staged_programs.display()
        )
    })?;
    if let Err(error) = fs::create_dir(&staged_diagnostics) {
        let _ = fs::remove_dir_all(&staged_programs);
        return Err(format!(
            "could not create staging directory `{}`: {error}",
            staged_diagnostics.display()
        ));
    }
    let staged_result = (|| {
        for (file_name, contents) in &generated.program_pages {
            fs::write(staged_programs.join(file_name), contents).map_err(|error| {
                format!("could not stage generated page `{file_name}`: {error}")
            })?;
        }
        for (file_name, contents) in &generated.diagnostic_pages {
            fs::write(staged_diagnostics.join(file_name), contents).map_err(|error| {
                format!("could not stage generated diagnostic page `{file_name}`: {error}")
            })?;
        }
        let current_summary = fs::read_to_string(&summary)
            .map_err(|error| format!("could not read `{}`: {error}", summary.display()))?;
        let updated_summary = replace_summary_block(
            &current_summary,
            PROGRAM_SUMMARY_START,
            PROGRAM_SUMMARY_END,
            &generated.program_summary_block,
        )?;
        let updated_summary = replace_summary_block(
            &updated_summary,
            DIAGNOSTIC_SUMMARY_START,
            DIAGNOSTIC_SUMMARY_END,
            &generated.diagnostic_summary_block,
        )?;
        fs::write(&staged_summary, updated_summary)
            .map_err(|error| format!("could not stage `{}`: {error}", summary.display()))
    })();
    if let Err(error) = staged_result {
        let _ = fs::remove_dir_all(&staged_programs);
        let _ = fs::remove_dir_all(&staged_diagnostics);
        let _ = fs::remove_file(&staged_summary);
        return Err(error);
    }

    let had_programs = programs.exists();
    let had_diagnostics = diagnostics.exists();
    if had_programs {
        fs::rename(&programs, &backup_programs).map_err(|error| {
            format!(
                "could not back up `{}` before replacement: {error}",
                programs.display()
            )
        })?;
    }
    if had_diagnostics && let Err(error) = fs::rename(&diagnostics, &backup_diagnostics) {
        if had_programs {
            let _ = fs::rename(&backup_programs, &programs);
        }
        let _ = fs::remove_dir_all(&staged_programs);
        let _ = fs::remove_dir_all(&staged_diagnostics);
        let _ = fs::remove_file(&staged_summary);
        return Err(format!(
            "could not back up `{}` before replacement: {error}",
            diagnostics.display()
        ));
    }
    if let Err(error) = fs::rename(&staged_programs, &programs) {
        if had_programs {
            let _ = fs::rename(&backup_programs, &programs);
        }
        if had_diagnostics {
            let _ = fs::rename(&backup_diagnostics, &diagnostics);
        }
        let _ = fs::remove_dir_all(&staged_diagnostics);
        let _ = fs::remove_file(&staged_summary);
        return Err(format!(
            "could not install generated program reference: {error}"
        ));
    }
    if let Err(error) = fs::rename(&staged_diagnostics, &diagnostics) {
        restore_generated_tree(&programs, &backup_programs, had_programs);
        if had_diagnostics {
            let _ = fs::rename(&backup_diagnostics, &diagnostics);
        }
        let _ = fs::remove_file(&staged_summary);
        return Err(format!(
            "could not install generated diagnostic reference: {error}"
        ));
    }

    if let Err(error) = fs::rename(&summary, &backup_summary) {
        restore_generated_tree(&programs, &backup_programs, had_programs);
        restore_generated_tree(&diagnostics, &backup_diagnostics, had_diagnostics);
        let _ = fs::remove_file(&staged_summary);
        return Err(format!(
            "could not back up `{}` before replacement: {error}",
            summary.display()
        ));
    }
    if let Err(error) = fs::rename(&staged_summary, &summary) {
        let _ = fs::rename(&backup_summary, &summary);
        restore_generated_tree(&programs, &backup_programs, had_programs);
        restore_generated_tree(&diagnostics, &backup_diagnostics, had_diagnostics);
        return Err(format!("could not install generated navigation: {error}"));
    }

    if had_programs {
        fs::remove_dir_all(&backup_programs).map_err(|error| {
            format!(
                "generated reference was updated but old backup `{}` could not be removed: {error}",
                backup_programs.display()
            )
        })?;
    }
    if had_diagnostics {
        fs::remove_dir_all(&backup_diagnostics).map_err(|error| {
            format!(
                "generated reference was updated but old backup `{}` could not be removed: {error}",
                backup_diagnostics.display()
            )
        })?;
    }
    fs::remove_file(&backup_summary).map_err(|error| {
        format!(
            "generated reference was updated but old backup `{}` could not be removed: {error}",
            backup_summary.display()
        )
    })?;
    Ok(())
}

fn restore_generated_tree(current: &Path, backup: &Path, had_tree: bool) {
    let failed = current.with_extension(format!("failed-{}", std::process::id()));
    if fs::rename(current, &failed).is_ok() {
        if had_tree {
            let _ = fs::rename(backup, current);
        }
        let _ = fs::remove_dir_all(failed);
    }
}

fn replace_summary_block(
    summary: &str,
    start_marker: &str,
    end_marker: &str,
    replacement: &str,
) -> Result<String> {
    let start = summary
        .find(start_marker)
        .ok_or_else(|| format!("docs/SUMMARY.md is missing `{start_marker}`"))?;
    let after_start = start + start_marker.len();
    if summary[after_start..].contains(start_marker) {
        return Err(format!(
            "docs/SUMMARY.md contains more than one `{start_marker}`"
        ));
    }
    let relative_end = summary[after_start..]
        .find(end_marker)
        .ok_or_else(|| format!("docs/SUMMARY.md is missing `{end_marker}`"))?;
    let end = after_start + relative_end + end_marker.len();
    if summary[end..].contains(end_marker) {
        return Err(format!(
            "docs/SUMMARY.md contains more than one `{end_marker}`"
        ));
    }
    let mut updated = String::with_capacity(summary.len() - (end - start) + replacement.len());
    updated.push_str(&summary[..start]);
    updated.push_str(replacement);
    updated.push_str(&summary[end..]);
    Ok(updated)
}

fn reject_incomplete_transactions(root: &Path) -> Result<()> {
    for directory in [root.join("docs"), root.join("docs/reference")] {
        let entries = fs::read_dir(&directory)
            .map_err(|error| format!("could not read `{}`: {error}", directory.display()))?;
        for entry in entries {
            let entry = entry.map_err(|error| {
                format!(
                    "could not inspect generator transaction paths in `{}`: {error}",
                    directory.display()
                )
            })?;
            let name = entry.file_name();
            let name = name.to_string_lossy();
            if name.starts_with(".programs-stage-")
                || name.starts_with(".programs-backup-")
                || name.starts_with(".diagnostics-stage-")
                || name.starts_with(".diagnostics-backup-")
                || name.starts_with(".SUMMARY-stage-")
                || name.starts_with(".SUMMARY-backup-")
            {
                return Err(format!(
                    "incomplete prior reference generation remains at `{}`",
                    entry.path().display()
                ));
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn generated() -> GeneratedReference {
        GeneratedReference {
            program_pages: BTreeMap::from([(
                "index.md".to_owned(),
                format!("{GENERATED_MARKER}\n\n# Programs and composition\n"),
            )]),
            diagnostic_pages: BTreeMap::from([(
                "index.md".to_owned(),
                format!("{GENERATED_MARKER}\n\n# Diagnostic index\n"),
            )]),
            program_summary_block: format!(
                "{PROGRAM_SUMMARY_START}\n- [Programs and composition](reference/programs/index.md)\n  - [`clip` and stack blocks](reference/language/composition-forms.md)\n{PROGRAM_SUMMARY_END}"
            ),
            diagnostic_summary_block: format!(
                "{DIAGNOSTIC_SUMMARY_START}\n- [Diagnostics](reference/diagnostics/index.md)\n{DIAGNOSTIC_SUMMARY_END}"
            ),
        }
    }

    fn repository() -> tempfile::TempDir {
        let directory = tempfile::tempdir().expect("temporary repository");
        fs::create_dir_all(directory.path().join("docs/reference/programs"))
            .expect("program directory");
        fs::create_dir_all(directory.path().join("docs/reference/diagnostics"))
            .expect("diagnostic directory");
        fs::write(
            directory.path().join("docs/SUMMARY.md"),
            format!(
                "# Summary\n\n{PROGRAM_SUMMARY_START}\nold\n{PROGRAM_SUMMARY_END}\n\
                 {DIAGNOSTIC_SUMMARY_START}\nold\n{DIAGNOSTIC_SUMMARY_END}\n"
            ),
        )
        .expect("summary");
        directory
    }

    #[test]
    fn write_replaces_the_owned_tree_and_summary_as_one_operation() {
        let repository = repository();
        let obsolete = repository
            .path()
            .join("docs/reference/programs/obsolete.md");
        fs::write(&obsolete, "obsolete").expect("obsolete page");
        let obsolete_diagnostic = repository
            .path()
            .join("docs/reference/diagnostics/obsolete.md");
        fs::write(&obsolete_diagnostic, "obsolete").expect("obsolete diagnostic page");

        write_generated(repository.path(), &generated()).expect("write generated reference");
        check_generated(repository.path(), &generated()).expect("current generated reference");

        assert!(!obsolete.exists());
        assert!(!obsolete_diagnostic.exists());
        assert_eq!(
            fs::read_to_string(repository.path().join("docs/reference/programs/index.md"))
                .expect("generated index"),
            format!("{GENERATED_MARKER}\n\n# Programs and composition\n")
        );
        assert_eq!(
            fs::read_to_string(
                repository
                    .path()
                    .join("docs/reference/diagnostics/index.md")
            )
            .expect("generated diagnostic index"),
            format!("{GENERATED_MARKER}\n\n# Diagnostic index\n")
        );
        assert!(
            fs::read_to_string(repository.path().join("docs/SUMMARY.md"))
                .expect("summary")
                .contains(
                    "  - [`clip` and stack blocks](reference/language/composition-forms.md)\n\
                     <!-- END GENERATED PROGRAM REFERENCE NAVIGATION -->"
                )
        );
        assert!(
            fs::read_to_string(repository.path().join("docs/SUMMARY.md"))
                .expect("summary")
                .contains(
                    "- [Diagnostics](reference/diagnostics/index.md)\n\
                     <!-- END GENERATED DIAGNOSTIC REFERENCE NAVIGATION -->"
                )
        );
    }

    #[test]
    fn check_reports_stale_and_obsolete_generated_files() {
        let repository = repository();
        fs::write(
            repository.path().join("docs/reference/programs/index.md"),
            "stale",
        )
        .expect("stale page");
        fs::write(
            repository
                .path()
                .join("docs/reference/programs/obsolete.md"),
            "obsolete",
        )
        .expect("obsolete page");
        fs::write(
            repository
                .path()
                .join("docs/reference/diagnostics/index.md"),
            "stale",
        )
        .expect("stale diagnostic page");
        fs::write(
            repository
                .path()
                .join("docs/reference/diagnostics/obsolete.md"),
            "obsolete",
        )
        .expect("obsolete diagnostic page");

        let error =
            check_generated(repository.path(), &generated()).expect_err("stale generated files");

        assert!(error.contains("generated bytes differ"), "{error}");
        assert!(error.contains("obsolete"), "{error}");
        assert!(error.contains("docs/SUMMARY.md differs"), "{error}");
    }

    #[test]
    fn diagnostic_code_scanner_finds_complete_tokens() {
        assert_eq!(
            diagnostic_codes_in("`E_ONE` E_TWO_2 E_ lower E_THREE."),
            BTreeSet::from([
                "E_ONE".to_owned(),
                "E_THREE".to_owned(),
                "E_TWO_2".to_owned()
            ])
        );
    }
}
