//! Deterministic generator for the checked-in built-in program reference.

use std::collections::{BTreeMap, BTreeSet};
use std::ffi::OsString;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use clipasm::reference::{
    self, BodyInitialValueRole, BodyOutputs, BuiltinCategory, BuiltinProgram, Cardinality,
    TimelineBehavior,
};

const GENERATED_MARKER: &str =
    "<!-- Generated by clipasm-reference-docs. Do not edit directly. -->";
const SUMMARY_START: &str = "<!-- BEGIN GENERATED PROGRAM REFERENCE NAVIGATION -->";
const SUMMARY_END: &str = "<!-- END GENERATED PROGRAM REFERENCE NAVIGATION -->";

type Result<T> = std::result::Result<T, String>;

/// Execute the generator's `write` or `check` mode.
///
/// # Errors
///
/// Returns a human-readable error for invalid arguments, catalog drift,
/// stale generated files, or filesystem failures.
pub fn run(arguments: impl IntoIterator<Item = OsString>) -> Result<()> {
    let arguments = arguments.into_iter().collect::<Vec<_>>();
    let [mode] = arguments.as_slice() else {
        return Err("usage: clipasm-reference-docs <write|check>".to_owned());
    };
    let mode = mode
        .to_str()
        .ok_or_else(|| "generator mode must be valid UTF-8".to_owned())?;
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .ok_or_else(|| "could not locate the ClipAsm repository root".to_owned())?;
    let generated = generate(root)?;
    match mode {
        "write" => {
            write_generated(root, &generated)?;
            println!(
                "updated {} generated built-in program reference pages",
                generated.pages.len()
            );
            Ok(())
        }
        "check" => {
            check_generated(root, &generated)?;
            println!(
                "{} generated built-in program reference pages are current",
                generated.pages.len()
            );
            Ok(())
        }
        _ => Err(format!(
            "unknown generator mode `{mode}`; expected `write` or `check`"
        )),
    }
}

#[derive(Debug)]
struct GeneratedReference {
    pages: BTreeMap<String, String>,
    summary_block: String,
}

fn generate(root: &Path) -> Result<GeneratedReference> {
    let programs = reference::builtin_programs();
    validate_catalog(root, &programs)?;

    let mut pages = BTreeMap::new();
    pages.insert("index.md".to_owned(), render_index(&programs));
    for program in &programs {
        let file_name = format!("{}.md", program.name());
        if pages
            .insert(file_name.clone(), render_program(program))
            .is_some()
        {
            return Err(format!(
                "two built-in programs map to generated page `{file_name}`"
            ));
        }
    }

    Ok(GeneratedReference {
        pages,
        summary_block: render_summary_block(&programs),
    })
}

fn validate_catalog(root: &Path, programs: &[BuiltinProgram]) -> Result<()> {
    if programs.is_empty() {
        return Err("built-in catalog is empty".to_owned());
    }

    let mut names = BTreeSet::new();
    let mut routes = BTreeSet::new();
    let mut categories = BTreeSet::new();
    for program in programs {
        if !names.insert(program.name()) {
            return Err(format!("duplicate built-in program `{}`", program.name()));
        }
        if !program
            .name()
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'_')
        {
            return Err(format!(
                "built-in program `{}` does not map to a safe stable route",
                program.name()
            ));
        }
        let route = program.documentation_route();
        if !routes.insert(route.clone()) {
            return Err(format!("duplicate built-in documentation route `{route}`"));
        }
        if route != format!("reference/programs/{}.html", program.name()) {
            return Err(format!(
                "built-in program `{}` has unexpected route `{route}`",
                program.name()
            ));
        }
        if program.summary().trim().is_empty() || program.summary().chars().any(char::is_control) {
            return Err(format!(
                "built-in program `{}` has an invalid summary",
                program.name()
            ));
        }
        categories.insert(program.category());
        validate_example(program)?;
        for related in program.related_programs() {
            if !names.contains(related.as_str())
                && !programs.iter().any(|candidate| candidate.name() == related)
            {
                return Err(format!(
                    "built-in program `{}` links to unknown related program `{related}`",
                    program.name()
                ));
            }
        }
        for diagnostic in program.diagnostics() {
            if !diagnostic.starts_with("E_")
                || !diagnostic
                    .bytes()
                    .all(|byte| byte.is_ascii_uppercase() || byte.is_ascii_digit() || byte == b'_')
            {
                return Err(format!(
                    "built-in program `{}` has invalid diagnostic code `{diagnostic}`",
                    program.name()
                ));
            }
        }
        for parameter in program.parameters() {
            if !parameter.is_required()
                && parameter.default().is_none()
                && parameter.omission_behavior().is_none()
            {
                return Err(format!(
                    "optional parameter `{}.{}` has neither a catalog default nor documented contextual behavior",
                    program.name(),
                    parameter.name()
                ));
            }
        }
    }

    let expected_categories = BuiltinCategory::ALL.into_iter().collect::<BTreeSet<_>>();
    if categories != expected_categories {
        return Err("one or more built-in program categories are empty".to_owned());
    }

    for path in [
        "docs/reference/language/stack-binding.md",
        "docs/reference/language/statements-and-calls.md",
        "docs/reference/cli.md",
    ] {
        if !root.join(path).is_file() {
            return Err(format!(
                "generated reference link target is missing: {path}"
            ));
        }
    }
    Ok(())
}

fn validate_example(program: &BuiltinProgram) -> Result<()> {
    let source = example_source(program);
    let path = PathBuf::from(format!("{}-reference.clipasm", program.name()));
    let package = clipasm::language::parse_str(&path, &source).map_err(|error| {
        format!(
            "built-in program `{}` example does not parse:\n{error}",
            program.name()
        )
    })?;
    let compiled = clipasm::compiler::compile(&package).map_err(|error| {
        format!(
            "built-in program `{}` example does not compile:\n{error}",
            program.name()
        )
    })?;
    if !compiled
        .explain()
        .iter()
        .any(|entry| entry.construct() == program.name())
    {
        return Err(format!(
            "built-in program `{}` example does not invoke that program",
            program.name()
        ));
    }
    let expectation = program.example_expectation();
    let actual_outputs = compiled
        .outputs()
        .iter()
        .map(|output| output.value_type())
        .collect::<Vec<_>>();
    if actual_outputs != expectation.outputs() {
        return Err(format!(
            "built-in program `{}` example produced {:?}, expected {:?}",
            program.name(),
            actual_outputs,
            expectation.outputs()
        ));
    }
    if let Some(expected_frames) = expectation.expected_frames() {
        let actual_frames = compiled
            .result_domain()
            .ok_or_else(|| {
                format!(
                    "built-in program `{}` example has no deterministic Video domain",
                    program.name()
                )
            })?
            .frames()
            .0;
        if actual_frames != expected_frames {
            return Err(format!(
                "built-in program `{}` example produced {actual_frames} frames, expected {expected_frames}",
                program.name()
            ));
        }
    }
    Ok(())
}

fn example_source(program: &BuiltinProgram) -> String {
    format!("clipasm 1\n\n{}\n", program.example().trim())
}

fn render_index(programs: &[BuiltinProgram]) -> String {
    let mut output = generated_header(
        "Built-in programs",
        "These are ClipAsm's built-in programs. Imported project programs are not included.",
    );
    output.push_str(
        "The type shapes below are reference notation, not ClipAsm declaration syntax. \
         See [statements and calls](../language/statements-and-calls.md) for authored syntax.\n\n",
    );
    for category in BuiltinCategory::ALL {
        writeln!(output, "## {}\n", category.label()).expect("write String");
        output.push_str("| Program | Summary | Type shape | Properties |\n");
        output.push_str("| --- | --- | --- | --- |\n");
        for program in programs
            .iter()
            .filter(|program| program.category() == category)
        {
            let properties = match (program.is_generic(), program.body().is_some()) {
                (true, true) => "generic; accepts a body",
                (true, false) => "generic",
                (false, true) => "accepts a body",
                (false, false) => "—",
            };
            writeln!(
                output,
                "| [`{0}`]({0}.md) | {1} | `{2}` | {3} |",
                program.name(),
                markdown_cell(program.summary()),
                markdown_cell(&type_shape(program)),
                properties,
            )
            .expect("write String");
        }
        output.push('\n');
    }
    output
}

#[expect(
    clippy::too_many_lines,
    reason = "the linear renderer keeps one generated page's section order visible in one place"
)]
fn render_program(program: &BuiltinProgram) -> String {
    let mut output = generated_header(program.name(), program.summary());

    output.push_str("## Call shape\n\n");
    writeln!(output, "```text\n{}\n```\n", program.call_shape()).expect("write String");
    output.push_str("This is call-shape notation for lookup, not ClipAsm declaration syntax.\n\n");

    output.push_str("## Inputs\n\n");
    if program.inputs().is_empty() {
        output.push_str("This program has no graph-valued inputs.\n\n");
    } else {
        output.push_str("| Name | Type | Cardinality |\n| --- | --- | --- |\n");
        for input in program.inputs() {
            let cardinality = match input.cardinality() {
                Cardinality::One => "exactly one".to_owned(),
                Cardinality::Variadic { minimum } => format!("one or more (minimum {minimum})"),
                _ => "catalog-defined".to_owned(),
            };
            writeln!(
                output,
                "| `{}` | `{}` | {} |",
                input.name(),
                input.value_type(),
                cardinality
            )
            .expect("write String");
        }
        output.push('\n');
    }

    output.push_str("## Parameters\n\n");
    if program.parameters().is_empty() {
        output.push_str("This program has no scalar parameters.\n\n");
    } else {
        output.push_str("| Name | Type | Requirement | Default or omission behavior |\n");
        output.push_str("| --- | --- | --- | --- |\n");
        for parameter in program.parameters() {
            let requirement = if parameter.is_required() {
                "required"
            } else {
                "optional"
            };
            let default = if parameter.is_required() {
                "—".to_owned()
            } else {
                parameter.default().map_or_else(
                    || {
                        parameter
                            .omission_behavior()
                            .unwrap_or("No fixed default.")
                            .to_owned()
                    },
                    ToString::to_string,
                )
            };
            writeln!(
                output,
                "| `{}` | `{}` | {} | {} |",
                parameter.name(),
                markdown_cell(&parameter.parameter_type().to_string()),
                requirement,
                markdown_cell(&default)
            )
            .expect("write String");
        }
        output.push('\n');
    }

    output.push_str("## Outputs and binding\n\n");
    if program.outputs().is_empty() {
        output.push_str("This program produces no values.\n\n");
    } else {
        let outputs = program
            .outputs()
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(output, "Outputs: `{outputs}`.\n").expect("write String");
    }
    if program.is_generic() {
        output.push_str(
            "All `T` inputs and outputs use one homogeneous type: Video or Audio. \
             Use an explicit `<Video>` or `<Audio>` argument when the accessible \
             stack makes inference ambiguous.\n\n",
        );
    }
    writeln!(
        output,
        "Default stack access is **{}**. See [stack binding](../language/stack-binding.md) \
         for ownership and visibility rules.\n",
        program.stack_access()
    )
    .expect("write String");

    if let Some(body) = program.body() {
        output.push_str("## Body contract\n\n");
        output.push_str("The body begins with:\n\n");
        for initial in body.initial_values() {
            let role = match initial.role() {
                BodyInitialValueRole::Input { input } => {
                    format!("the complete `{input}` input")
                }
                BodyInitialValueRole::SelectedRange { input, parameter } => {
                    format!("the range selected from `{input}` by `{parameter}`")
                }
                _ => "a catalog-defined initial value".to_owned(),
            };
            writeln!(output, "- `{}` from {role}", initial.value_type()).expect("write String");
        }
        output.push_str("\nThe body must leave ");
        match body.outputs() {
            BodyOutputs::Exactly(outputs) => {
                let output_types = outputs
                    .iter()
                    .map(ToString::to_string)
                    .collect::<Vec<_>>()
                    .join(", ");
                write!(output, "exactly `{output_types}`").expect("write String");
            }
            BodyOutputs::Variadic {
                value_type,
                minimum,
            } => {
                write!(
                    output,
                    "at least {minimum} homogeneous `{value_type}` value(s)"
                )
                .expect("write String");
            }
            _ => output.push_str("the catalog-defined output sequence"),
        }
        output.push_str(".\n\n");
    }

    output.push_str("## Timeline behavior\n\n");
    writeln!(
        output,
        "{}\n",
        timeline_description(program.timeline_behavior())
    )
    .expect("write String");

    output.push_str("## Example\n\n");
    writeln!(output, "```clipasm\n{}```\n", example_source(program)).expect("write String");
    output.push_str("Expected validation result: ");
    let expectation = program.example_expectation();
    if expectation.outputs().is_empty() {
        output.push_str("no output values");
    } else {
        let outputs = expectation
            .outputs()
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(", ");
        write!(output, "`{outputs}`").expect("write String");
        if let Some(frames) = expectation.expected_frames() {
            write!(output, " with exactly {frames} project frames").expect("write String");
        } else if expectation.outputs() == [clipasm::model::ValueType::Video] {
            output.push_str(" with a source-dependent frame domain resolved during preflight");
        }
    }
    output.push_str(".\n\n");
    output.push_str(
        "This exact example is parsed and compiled by the reference checks; compilation \
         does not inspect the named media files.\n\n",
    );

    output.push_str("## Important behavior\n\n");
    for paragraph in program.behavior_notes() {
        writeln!(output, "- {paragraph}").expect("write String");
    }
    if program.behavior_notes().is_empty() {
        output.push_str("- The call follows the generated contract above.\n");
    }
    output.push('\n');

    if !program.constraints().is_empty() {
        output.push_str("## Constraints\n\n");
        for constraint in program.constraints() {
            writeln!(output, "- {constraint}").expect("write String");
        }
        output.push('\n');
    }

    if !program.diagnostics().is_empty() {
        output.push_str("## Selected diagnostics\n\n");
        output.push_str(
            "These are selected actionable diagnostics, not every error a call can produce.\n\n",
        );
        for diagnostic in program.diagnostics() {
            writeln!(output, "- `{diagnostic}`").expect("write String");
        }
        output.push('\n');
    }

    output.push_str("## Related reference\n\n");
    for related in program.related_programs() {
        writeln!(output, "- [`{related}`]({related}.md)").expect("write String");
    }
    output.push_str(
        "- [Statements and calls](../language/statements-and-calls.md)\n\
         - [Stack binding](../language/stack-binding.md)\n",
    );
    output
}

fn generated_header(title: &str, summary: &str) -> String {
    format!("{GENERATED_MARKER}\n\n# {title}\n\n{summary}\n\n")
}

fn type_shape(program: &BuiltinProgram) -> String {
    let inputs = program
        .inputs()
        .iter()
        .map(|input| match input.cardinality() {
            Cardinality::Variadic { .. } => format!("{}...", input.value_type()),
            _ => input.value_type().to_string(),
        })
        .collect::<Vec<_>>()
        .join(", ");
    let outputs = if program.outputs().is_empty() {
        "none".to_owned()
    } else {
        program
            .outputs()
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(", ")
    };
    format!("({inputs}) -> {outputs}")
}

fn timeline_description(behavior: &TimelineBehavior) -> String {
    match behavior {
        TimelineBehavior::Fresh => {
            "Creates a fresh timeline layout, or no layout when the program has no output."
                .to_owned()
        }
        TimelineBehavior::Identity { input } => {
            format!("Preserves the timeline layout of `{input}`.")
        }
        TimelineBehavior::Repeat { input } => format!(
            "`repeat(1)` preserves `{input}` as an identity. Larger counts create a fresh, \
             unindexed repeated timeline."
        ),
        TimelineBehavior::Concat { input } => {
            format!("Concatenates the ordered timeline layouts bound to `{input}`.")
        }
        TimelineBehavior::BodyConcat { inputs } => format!(
            "Initializes the body from {} and concatenates the homogeneous values it leaves.",
            inputs
                .iter()
                .map(|input| format!("`{input}`"))
                .collect::<Vec<_>>()
                .join(" and ")
        ),
        TimelineBehavior::Crop { input } => format!(
            "Crops `{input}` to the selected range and retains only placements proven to lie \
             completely inside it."
        ),
        TimelineBehavior::Replace { base } => format!(
            "Replaces the selected range in `{base}`, shifts later placements, and exposes the \
             inserted layout as `replacement`."
        ),
        TimelineBehavior::FlashCut { before, after } => format!(
            "Places `{before}` and `{after}` sequentially and exposes corresponding transition \
             regions."
        ),
        TimelineBehavior::Crossfade { before, after } => format!(
            "Overlaps the end of `{before}` with the start of `{after}` and exposes `before`, \
             `overlap`, and `after` regions."
        ),
        _ => "Uses the catalog-defined timeline behavior.".to_owned(),
    }
}

fn markdown_cell(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}

fn render_summary_block(programs: &[BuiltinProgram]) -> String {
    let mut output = format!("{SUMMARY_START}\n");
    output.push_str("- [Built-in programs](reference/programs/index.md)\n");
    for program in programs {
        writeln!(
            output,
            "  - [`{0}`](reference/programs/{0}.md)",
            program.name()
        )
        .expect("write String");
    }
    output.push_str(SUMMARY_END);
    output
}

fn check_generated(root: &Path, generated: &GeneratedReference) -> Result<()> {
    reject_incomplete_transactions(root)?;
    let directory = root.join("docs/reference/programs");
    let mut problems = Vec::new();
    if directory.is_dir() {
        let actual = fs::read_dir(&directory)
            .map_err(|error| format!("could not read `{}`: {error}", directory.display()))?
            .map(|entry| {
                entry.map_err(|error| format!("could not read generated directory entry: {error}"))
            })
            .collect::<Result<Vec<_>>>()?;
        let expected_names = generated.pages.keys().cloned().collect::<BTreeSet<_>>();
        for entry in actual {
            let file_name = entry.file_name().to_string_lossy().into_owned();
            if !expected_names.contains(&file_name) {
                problems.push(format!(
                    "obsolete or unowned generated path remains: docs/reference/programs/{file_name}"
                ));
            }
        }
        for (file_name, expected) in &generated.pages {
            let path = directory.join(file_name);
            match fs::read_to_string(&path) {
                Ok(actual) if actual == *expected => {}
                Ok(_) => problems.push(format!(
                    "generated bytes differ: docs/reference/programs/{file_name}"
                )),
                Err(error) => problems.push(format!(
                    "could not read generated page `docs/reference/programs/{file_name}`: {error}"
                )),
            }
        }
    } else {
        problems.push("generated program reference directory is missing".to_owned());
    }

    let summary_path = root.join("docs/SUMMARY.md");
    match fs::read_to_string(&summary_path) {
        Ok(summary) => match replace_summary_block(&summary, &generated.summary_block) {
            Ok(expected) if expected == summary => {}
            Ok(_) => {
                problems.push("generated program navigation in docs/SUMMARY.md differs".into());
            }
            Err(error) => problems.push(error),
        },
        Err(error) => problems.push(format!("could not read docs/SUMMARY.md: {error}")),
    }

    if problems.is_empty() {
        Ok(())
    } else {
        Err(format!(
            "generated built-in reference is stale:\n- {}",
            problems.join("\n- ")
        ))
    }
}

fn write_generated(root: &Path, generated: &GeneratedReference) -> Result<()> {
    reject_incomplete_transactions(root)?;
    let reference_directory = root.join("docs/reference");
    let programs = reference_directory.join("programs");
    let summary = root.join("docs/SUMMARY.md");
    let process = std::process::id();
    let staged_programs = reference_directory.join(format!(".programs-stage-{process}"));
    let backup_programs = reference_directory.join(format!(".programs-backup-{process}"));
    let staged_summary = root.join(format!("docs/.SUMMARY-stage-{process}"));
    let backup_summary = root.join(format!("docs/.SUMMARY-backup-{process}"));

    fs::create_dir(&staged_programs).map_err(|error| {
        format!(
            "could not create staging directory `{}`: {error}",
            staged_programs.display()
        )
    })?;
    let staged_result = (|| {
        for (file_name, contents) in &generated.pages {
            fs::write(staged_programs.join(file_name), contents).map_err(|error| {
                format!("could not stage generated page `{file_name}`: {error}")
            })?;
        }
        let current_summary = fs::read_to_string(&summary)
            .map_err(|error| format!("could not read `{}`: {error}", summary.display()))?;
        let updated_summary = replace_summary_block(&current_summary, &generated.summary_block)?;
        fs::write(&staged_summary, updated_summary)
            .map_err(|error| format!("could not stage `{}`: {error}", summary.display()))
    })();
    if let Err(error) = staged_result {
        let _ = fs::remove_dir_all(&staged_programs);
        let _ = fs::remove_file(&staged_summary);
        return Err(error);
    }

    let had_programs = programs.exists();
    if had_programs {
        fs::rename(&programs, &backup_programs).map_err(|error| {
            format!(
                "could not back up `{}` before replacement: {error}",
                programs.display()
            )
        })?;
    }
    if let Err(error) = fs::rename(&staged_programs, &programs) {
        if had_programs {
            let _ = fs::rename(&backup_programs, &programs);
        }
        let _ = fs::remove_file(&staged_summary);
        return Err(format!(
            "could not install generated program reference: {error}"
        ));
    }

    if let Err(error) = fs::rename(&summary, &backup_summary) {
        restore_programs(&programs, &backup_programs, had_programs);
        let _ = fs::remove_file(&staged_summary);
        return Err(format!(
            "could not back up `{}` before replacement: {error}",
            summary.display()
        ));
    }
    if let Err(error) = fs::rename(&staged_summary, &summary) {
        let _ = fs::rename(&backup_summary, &summary);
        restore_programs(&programs, &backup_programs, had_programs);
        return Err(format!("could not install generated navigation: {error}"));
    }

    if had_programs {
        fs::remove_dir_all(&backup_programs).map_err(|error| {
            format!(
                "generated reference was updated but old backup `{}` could not be removed: {error}",
                backup_programs.display()
            )
        })?;
    }
    fs::remove_file(&backup_summary).map_err(|error| {
        format!(
            "generated reference was updated but old backup `{}` could not be removed: {error}",
            backup_summary.display()
        )
    })?;
    Ok(())
}

fn restore_programs(programs: &Path, backup: &Path, had_programs: bool) {
    let failed = programs.with_extension(format!("failed-{}", std::process::id()));
    if fs::rename(programs, &failed).is_ok() {
        if had_programs {
            let _ = fs::rename(backup, programs);
        }
        let _ = fs::remove_dir_all(failed);
    }
}

fn replace_summary_block(summary: &str, replacement: &str) -> Result<String> {
    let start = summary
        .find(SUMMARY_START)
        .ok_or_else(|| format!("docs/SUMMARY.md is missing `{SUMMARY_START}`"))?;
    let after_start = start + SUMMARY_START.len();
    if summary[after_start..].contains(SUMMARY_START) {
        return Err(format!(
            "docs/SUMMARY.md contains more than one `{SUMMARY_START}`"
        ));
    }
    let relative_end = summary[after_start..]
        .find(SUMMARY_END)
        .ok_or_else(|| format!("docs/SUMMARY.md is missing `{SUMMARY_END}`"))?;
    let end = after_start + relative_end + SUMMARY_END.len();
    if summary[end..].contains(SUMMARY_END) {
        return Err(format!(
            "docs/SUMMARY.md contains more than one `{SUMMARY_END}`"
        ));
    }
    let mut updated = String::with_capacity(summary.len() - (end - start) + replacement.len());
    updated.push_str(&summary[..start]);
    updated.push_str(replacement);
    updated.push_str(&summary[end..]);
    Ok(updated)
}

fn reject_incomplete_transactions(root: &Path) -> Result<()> {
    for directory in [root.join("docs"), root.join("docs/reference")] {
        let entries = fs::read_dir(&directory)
            .map_err(|error| format!("could not read `{}`: {error}", directory.display()))?;
        for entry in entries {
            let entry = entry.map_err(|error| {
                format!(
                    "could not inspect generator transaction paths in `{}`: {error}",
                    directory.display()
                )
            })?;
            let name = entry.file_name();
            let name = name.to_string_lossy();
            if name.starts_with(".programs-stage-")
                || name.starts_with(".programs-backup-")
                || name.starts_with(".SUMMARY-stage-")
                || name.starts_with(".SUMMARY-backup-")
            {
                return Err(format!(
                    "incomplete prior reference generation remains at `{}`",
                    entry.path().display()
                ));
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn generated() -> GeneratedReference {
        GeneratedReference {
            pages: BTreeMap::from([(
                "index.md".to_owned(),
                format!("{GENERATED_MARKER}\n\n# Built-in programs\n"),
            )]),
            summary_block: format!(
                "{SUMMARY_START}\n- [Built-in programs](reference/programs/index.md)\n{SUMMARY_END}"
            ),
        }
    }

    fn repository() -> tempfile::TempDir {
        let directory = tempfile::tempdir().expect("temporary repository");
        fs::create_dir_all(directory.path().join("docs/reference/programs"))
            .expect("program directory");
        fs::write(
            directory.path().join("docs/SUMMARY.md"),
            format!("# Summary\n\n{SUMMARY_START}\nold\n{SUMMARY_END}\n"),
        )
        .expect("summary");
        directory
    }

    #[test]
    fn write_replaces_the_owned_tree_and_summary_as_one_operation() {
        let repository = repository();
        let obsolete = repository
            .path()
            .join("docs/reference/programs/obsolete.md");
        fs::write(&obsolete, "obsolete").expect("obsolete page");

        write_generated(repository.path(), &generated()).expect("write generated reference");
        check_generated(repository.path(), &generated()).expect("current generated reference");

        assert!(!obsolete.exists());
        assert_eq!(
            fs::read_to_string(repository.path().join("docs/reference/programs/index.md"))
                .expect("generated index"),
            format!("{GENERATED_MARKER}\n\n# Built-in programs\n")
        );
        assert!(
            fs::read_to_string(repository.path().join("docs/SUMMARY.md"))
                .expect("summary")
                .contains(
                    "- [Built-in programs](reference/programs/index.md)\n\
                     <!-- END GENERATED PROGRAM REFERENCE NAVIGATION -->"
                )
        );
    }

    #[test]
    fn check_reports_stale_and_obsolete_generated_files() {
        let repository = repository();
        fs::write(
            repository.path().join("docs/reference/programs/index.md"),
            "stale",
        )
        .expect("stale page");
        fs::write(
            repository
                .path()
                .join("docs/reference/programs/obsolete.md"),
            "obsolete",
        )
        .expect("obsolete page");

        let error =
            check_generated(repository.path(), &generated()).expect_err("stale generated files");

        assert!(error.contains("generated bytes differ"), "{error}");
        assert!(error.contains("obsolete"), "{error}");
        assert!(error.contains("docs/SUMMARY.md differs"), "{error}");
    }
}
