#!/usr/bin/env python3
"""Verify that files embedded by the CLI and its examples ship in the crate."""

from __future__ import annotations

from pathlib import Path
import subprocess
import sys


REQUIRED_PATHS = frozenset(
    {
        "src/cli/init.rs",
        "examples/assets/evening.png",
        "examples/assets/meadow.png",
        "examples/assets/morning.png",
        "examples/scenic-sequence.clipasm",
        "examples/starter/.gitignore",
        "examples/starter/clipasm.toml",
        "examples/starter/README.md",
        "examples/programs/brighten/brighten.py",
    }
)
GENERATED_REFERENCE_MARKER = (
    "<!-- Generated by clipasm-reference-docs. Do not edit directly. -->"
)
FORBIDDEN_PREFIXES = ("tools/reference-docs/",)


def repository_root() -> Path:
    return Path(__file__).resolve().parent.parent


def packaged_paths(root: Path) -> set[str]:
    try:
        result = subprocess.run(
            ["cargo", "package", "--list", "--locked", "--allow-dirty"],
            cwd=root,
            check=True,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        print("package contents check failed: cargo is not installed", file=sys.stderr)
        raise SystemExit(1) from None
    except subprocess.CalledProcessError as error:
        print("package contents check failed: cargo package --list failed", file=sys.stderr)
        if error.stderr:
            print(error.stderr, file=sys.stderr, end="" if error.stderr.endswith("\n") else "\n")
        raise SystemExit(error.returncode) from None
    return set(result.stdout.splitlines())


def generated_reference_paths(root: Path, reference_kind: str) -> set[str]:
    directory = root / "docs/reference" / reference_kind
    paths: set[str] = set()
    for path in sorted(directory.glob("*.md")):
        if not path.read_text(encoding="utf-8").startswith(GENERATED_REFERENCE_MARKER):
            print(
                f"package contents check failed: generated marker is missing from "
                f"{path.relative_to(root)}",
                file=sys.stderr,
            )
            raise SystemExit(1)
        paths.add(path.relative_to(root).as_posix())
    if not paths:
        print(
            f"package contents check failed: no generated {reference_kind} pages found",
            file=sys.stderr,
        )
        raise SystemExit(1)
    return paths


def main() -> int:
    root = repository_root()
    packaged = packaged_paths(root)
    required = (
        REQUIRED_PATHS
        | generated_reference_paths(root, "programs")
        | {"docs/diagnostics/index.html"}
    )
    missing = sorted(required - packaged)
    if missing:
        print("package contents check failed: required paths are missing:", file=sys.stderr)
        for path in missing:
            print(f"- {path}", file=sys.stderr)
        return 1
    forbidden = sorted(
        path
        for path in packaged
        if any(path.startswith(prefix) for prefix in FORBIDDEN_PREFIXES)
    )
    if forbidden:
        print("package contents check failed: workspace tools were packaged:", file=sys.stderr)
        for path in forbidden:
            print(f"- {path}", file=sys.stderr)
        return 1
    print(
        "package contains generated program pages, the standalone diagnostics page, initializer sources, assets, "
        "starter files, and external examples without workspace tools"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
